### ISSUE TITLE
SpatialCrossResponseNormalization bug

### ISSUE THREAD

**Issue by qassemoquab** [szagoruyko/imagine-nn#12]
When the input tensor is too big, number of blocks exceeds 65535, which causes crashes when compiling with arch=sm_20. That causes issues when trying to loadcaffe VGG_M network with 'cudnn', which uses inn.SCRN .

Any reason for not using sm_35 ?

**Comment by szagoruyko** [comment]
you can just use cudnn. I will update loadcaffe in a few days to support R3.

**Comment by szagoruyko** [comment]
fixed by https://github.com/szagoruyko/imagine-nn/pull/16
