### ISSUE TITLE
inn.SpatialSameResponseNormalization.listModules() not working

### ISSUE THREAD

**Issue by 0wu** [szagoruyko/imagine-nn#14]
The following code 
```
require 'inn'
local m=inn.SpatialSameResponseNormalization(3,0.00005,0.75)
print(m:listModules())
```
gives an error
```
/home/tingfan/dnn/torch/install/share/lua/5.1/nn/Module.lua:286: attempt to index a nil value
stack traceback:
        /home/tingfan/dnn/torch/install/share/lua/5.1/nn/Module.lua:286: in function 'listModules'
        [string "print(m:listModules())"]:1: in main chunk
        [C]: in function 'xpcall'
        ...e/tingfan/dnn/torch/install/share/lua/5.1/trepl/init.lua:648: in function 'repl'
        .../dnn/torch/install/lib/luarocks/rocks/trepl/scm-1/bin/th:185: in main chunk
        [C]: at 0x00406670
```
because the inherited listModule() assumes self:modules is an [] index-able array.

One way to fix it it to add its own listModule() member function
```
function inn.SpatialSameResponseNormalization:listModules()
    return {m.modules}
end
```
Or making nn.Sequential.__index() call Sequential:get().  I would prefer the later one but not sure if it is legit.

**Comment by fmassa** [comment]
I think an even simpler solution would be to rename `modules` to something else, like `module`. Thanks for pointing it out !

**Comment by 0wu** [comment]
That works... but it is also nice to see through the shell of SpatialSameResponseNormalization realizing there is a Sequantial module and its members inside

**Comment by szagoruyko** [comment]
fixed now
