### ISSUE TITLE
thoughts on porting averagepooling ceil mode into opencl?

### ISSUE THREAD

**Issue by hughperkins** [szagoruyko/imagine-nn#15]
Hi Sergey,

Looks like some neural-style models could plausibly benefit from averagepooling.  Therefore needs `ceil` mode.  So, I'm pondering vaguely porting your inn averagepooling to cl somehow/somewhere.  Seems like the easiest way to do this might be to fork inn itself, eg to 'clinn'?  (Otherwise needs to port everything into `nn`, which whilst a good long-term goal, might take more than a few days probably I would think?)

Hugh

(PS I suppose one other way would be to port directly into clnn, and then hack neural-style's `loadcaffe_wrapper.lua`, that might be easier actually.... still pondering...)

**Comment by szagoruyko** [comment]
Hi Hugh, check this https://github.com/torch/cunn/pull/134 it will go into nn&cunn soon

**Comment by hughperkins** [comment]
Awesomeness!  Thanks! :-)
